### ISSUE TITLE
Hero image on static site not rendering

### ISSUE THREAD

**Issue by jdkelley** [jpryor83/aviation#3]
@jpryor83  - The hero image on https://jpryor83.github.io/aviation/ is not rendering. 

It looks like you have been making changes to the `master` branch but not pulling those changes into the `gh-pages` branch which is actually what is displayed at https://jpryor83.github.io/aviation/

**Comment by jpryor83** [comment]
@jdkelley - so i guess i just create a PR from Master into gh-pages, right?

**Comment by jdkelley** [comment]
@jpryor83 - That's right. And then merge it.

**Comment by jdkelley** [comment]
Like this one: #4

**Comment by jdkelley** [comment]
nm - I don't think that will fix it since it only contains my README change

**Comment by forgeweldapps** [comment]
# Solved! I uploaded the video to vimeo, and pointed to it and it works now. See this PR:
https://github.com/jpryor83/aviation/pull/5
